#!/bin/bash

if [ -f /usr/share/X11/xkb/rules/evdev.xml.bak ]; 
    then echo "evdev.xml.bak found - reverting to evdev.xml" && rm /usr/share/X11/xkb/rules/evdev.xml && cp /usr/share/X11/xkb/rules/evdev.xml.bak /usr/share/X11/xkb/rules/evdev.xml; 

    else grep "Guarani" "/usr/share/X11/xkb/rules/evdev.xml"; echo "Guarani still exist on evdev, please remove manually from /usr/share/X11/xkb/rules/evdev.xml";
fi
